version: "3"

services:
  client:
    image: tokenbreeze-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    image: tokenbreeze-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
