# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install Dependencies
        run: |
          cd server
          npm install
          npm install bun

      - name: Run tests
        env:
          REDIS_URL: ${{secrets.REDIS_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DIRECT_URL: ${{secrets.DIRECT_URL}}
          COIN_MARKET_CAP_API_KEY: ${{secrets.COIN_MARKET_CAP_API_KEY}}
          COINGECKO_API_KEY: ${{secrets.COINGECKO_API_KEY}}
          COINGECKO_ROOT_URL: ${{secrets.COINGECKO_ROOT_URL}}
          NODE_ENV: ${{secrets.NODE_ENV}}
        run: |
          cd server
          npm run test:unit

      - name: Build
        run: |
          cd server
          npm run build --if-present
