# This workflow deploys the server to Google Cloud Run
# It requires the GCP_PROJECT_ID, GCP_SA_KEY, and GCP_REGION

name: Server Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          cd server
          bun install

      - name: Run tests
        env:
          REDIS_URL: ${{secrets.REDIS_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DIRECT_URL: ${{secrets.DIRECT_URL}}
          COIN_MARKET_CAP_API_KEY: ${{secrets.COIN_MARKET_CAP_API_KEY}}
          COINGECKO_API_KEY: ${{secrets.COINGECKO_API_KEY}}
          COINGECKO_ROOT_URL: ${{secrets.COINGECKO_ROOT_URL}}
          NODE_ENV: ${{secrets.NODE_ENV}}
        run: |
          cd server
          npm run test:unit

      - name: Build
        run: |
          cd server
          npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        run: |
          cd server
          gcloud run deploy tokenbreeze \
              --source=. \
              --allow-unauthenticated \
              --region=${{ secrets.GCP_REGION }} \
